# Generated by Django 6.0.1 on 2026-02-01 16:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
